// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuXIj3yiGfvrZh08RL2uuXeFINDtuyZLM',
    appId: '1:759054251135:web:1d28d4ef8448eea0513b4a',
    messagingSenderId: '759054251135',
    projectId: 'akvaryumurunsat-8edd0',
    authDomain: 'akvaryumurunsat-8edd0.firebaseapp.com',
    storageBucket: 'akvaryumurunsat-8edd0.firebasestorage.app',
    measurementId: 'G-96TF25PL3L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1QWOYgoUjpH4pbq72WXn10D92MrkB_FU',
    appId: '1:759054251135:android:1202ad56b7175452513b4a',
    messagingSenderId: '759054251135',
    projectId: 'akvaryumurunsat-8edd0',
    storageBucket: 'akvaryumurunsat-8edd0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUTcJVKaBcqIdoLlx7KgsC3F14dlyu5ao',
    appId: '1:759054251135:ios:188e8cf8a0db630a513b4a',
    messagingSenderId: '759054251135',
    projectId: 'akvaryumurunsat-8edd0',
    storageBucket: 'akvaryumurunsat-8edd0.firebasestorage.app',
    iosBundleId: 'com.example.akvaryumUrunUretsat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUTcJVKaBcqIdoLlx7KgsC3F14dlyu5ao',
    appId: '1:759054251135:ios:188e8cf8a0db630a513b4a',
    messagingSenderId: '759054251135',
    projectId: 'akvaryumurunsat-8edd0',
    storageBucket: 'akvaryumurunsat-8edd0.firebasestorage.app',
    iosBundleId: 'com.example.akvaryumUrunUretsat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuXIj3yiGfvrZh08RL2uuXeFINDtuyZLM',
    appId: '1:759054251135:web:21a66c7ee9cfc51f513b4a',
    messagingSenderId: '759054251135',
    projectId: 'akvaryumurunsat-8edd0',
    authDomain: 'akvaryumurunsat-8edd0.firebaseapp.com',
    storageBucket: 'akvaryumurunsat-8edd0.firebasestorage.app',
    measurementId: 'G-599VB2DNTZ',
  );

}